<a href="https://colab.research.google.com/github/HenryJi529/ColabNotebooks/blob/main/LecturePytorch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Fri Mar 10 13:22:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    29W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
torch.__version__

'1.13.1+cu116'

In [ ]:
import torch

if torch.cuda.is_available():
    print("CUDA is available!")
    device_count = torch.cuda.device_count()
    print(f"Number of available GPUs: {device_count}")
    for i in range(device_count):
        print(f"Device {i}: {torch.cuda.get_device_name(i)}")
        print(f"\tTotal memory: {torch.cuda.get_device_properties(i).total_memory / (1024**3):.2f} GB")
        print(f"\tMemory allocated: {torch.cuda.memory_allocated(i) / (1024**2):.2f} MB")
        print(f"\tMemory cached: {torch.cuda.memory_reserved(i) / (1024**2):.2f} MB")
else:
    print("CUDA is not available.")


CUDA is available!
Number of available GPUs: 1
Device 0: Tesla T4
	Total memory: 14.75 GB
	Memory allocated: 0.00 MB
	Memory cached: 0.00 MB


## InTroduce Tensor

### create tensor

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
 vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([1, 2])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor1 = torch.tensor([[[
    [1,2],[2,3]
    ]]])
tensor1

tensor([[[[1, 2],
          [2, 3]]]])

In [ ]:
tensor1.shape

torch.Size([1, 1, 2, 2])

In [ ]:
tensor1.ndim

4

In [ ]:
tensor1[0]

tensor([[[1, 2],
         [2, 3]]])

In [ ]:
tensor1[0][0]

tensor([[1, 2],
        [2, 3]])

In [ ]:
tensor1[0][0][0]

tensor([1, 2])

### random tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0094, 0.1130, 0.1151, 0.1192],
        [0.9256, 0.0972, 0.4197, 0.8970],
        [0.2414, 0.9506, 0.0870, 0.5084]])

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
random_tensor.ndim

2

In [ ]:
torch.rand(3,4,4)

tensor([[[0.3079, 0.7067, 0.9364, 0.3718],
         [0.4573, 0.8701, 0.1961, 0.8966],
         [0.8761, 0.5123, 0.9479, 0.8141],
         [0.1513, 0.0159, 0.5011, 0.9803]],

        [[0.2358, 0.8624, 0.0813, 0.0216],
         [0.8040, 0.7416, 0.5598, 0.9147],
         [0.9877, 0.8408, 0.5890, 0.9771],
         [0.5971, 0.9401, 0.7499, 0.2681]],

        [[0.4973, 0.4245, 0.6717, 0.2125],
         [0.4451, 0.1146, 0.6168, 0.7059],
         [0.5170, 0.2876, 0.5441, 0.0872],
         [0.0956, 0.1506, 0.8314, 0.0594]]])

### Zeros and Ones

In [ ]:
zeros1 = torch.zeros(3,4)
zeros1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros1 * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones1 = torch.ones(3,4)
ones1.dtype

torch.float32

### range of tensors

In [ ]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [ ]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.zeros_like(torch.arange(1,10,2))

tensor([0, 0, 0, 0, 0])

### tensor datatype

In [ ]:
float32_tensor = torch.tensor([3.0, 7, 8], dtype=torch.float32)
float32_tensor

tensor([3., 7., 8.])

In [ ]:
 float16_tensor = torch.tensor([3.0, 7, 8], dtype=torch.float16)

In [ ]:
float32_tensor * float16_tensor

tensor([ 9., 49., 64.])

### manipulating tensor

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication

In [ ]:
A = torch.rand(3,4)
A

tensor([[0.8248, 0.0343, 0.1994, 0.4511],
        [0.2220, 0.6522, 0.1316, 0.7023],
        [0.6760, 0.6763, 0.5829, 0.3251]])

In [ ]:
X = torch.rand(4)
X

tensor([0.7422, 0.8678, 0.2472, 0.6491])

In [ ]:
A @ X

tensor([0.9839, 1.2190, 1.4437])

In [ ]:
torch.matmul(A, X)

tensor([0.9839, 1.2190, 1.4437])

In [ ]:
A = torch.rand(3,40000)
X = torch.rand(40000)
torch.matmul(A, X)
%time

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.48 µs


In [ ]:
A = torch.rand(3,40000)
X = torch.rand(40000)
A @ X
%time

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.44 µs


In [ ]:
A.dtype

torch.float32

In [ ]:
A.type(torch.float64)

tensor([[0.4929, 0.7874, 0.6393,  ..., 0.6935, 0.6047, 0.2639],
        [0.2554, 0.1941, 0.9004,  ..., 0.3882, 0.2263, 0.2502],
        [0.2520, 0.6246, 0.3061,  ..., 0.7555, 0.5799, 0.7233]],
       dtype=torch.float64)

In [ ]:
A.T

tensor([[0.4929, 0.2554, 0.2520],
        [0.7874, 0.1941, 0.6246],
        [0.6393, 0.9004, 0.3061],
        ...,
        [0.6935, 0.3882, 0.7555],
        [0.6047, 0.2263, 0.5799],
        [0.2639, 0.2502, 0.7233]])

In [ ]:
torch.where(X>0.5)

(tensor([    0,     1,     4,  ..., 39992, 39995, 39996]),)

In [ ]:
  np.concatenate([np.array([1,1,1]).reshape(3,1), (np.array([1,1,1])*2).reshape(3,1)],axis=1)

array([[1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
np.array([1,1,2,3]).view(np.float64)

array([4.9e-324, 4.9e-324, 9.9e-324, 1.5e-323])

In [ ]:
X.size()

torch.Size([40000])

In [ ]:
X.shape

torch.Size([40000])

In [ ]:
X = torch.tensor([[[1,2],[3,4]]])
X1 = X.squeeze()
print(X,X1)

tensor([[[1, 2],
         [3, 4]]]) tensor([[1, 2],
        [3, 4]])


In [ ]:
X[0][0] = 5

In [ ]:
X

tensor([[[5, 5],
         [3, 4]]])

In [ ]:
X1

tensor([[5, 5],
        [3, 4]])

In [ ]:
X1[:,0]

tensor([5, 3])

### reproduction

In [ ]:
torch.manual_seed(43)
torch.randint(3, 14, (2, 2))

tensor([[ 6,  8],
        [ 8, 10]])

## Check GPU 

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
torch.cuda.device_count()

1

In [ ]:
import torch

if torch.cuda.is_available():
    print("CUDA is available!")
    device_count = torch.cuda.device_count()
    print(f"Number of available GPUs: {device_count}")
    for i in range(device_count):
        print(f"Device {i}: {torch.  cuda.get_device_name(i)}")
        print(f"\tTotal memory: {torch.cuda.get_device_properties(i).total_memory / (1024**3):.2f} GB")
        print(f"\tMemory allocated: {torch.cuda.memory_allocated(i) / (1024**2):.2f} MB")
        print(f"\tMemory cached: {torch.cuda.memory_reserved(i) / (1024**2):.2f} MB")
else:
    print("CUDA is not available.")

### Put tensor on GPU

In [ ]:
tensor = torch.tensor([1,2,3],device="cpu")
tensor.device

device(type='cpu')

In [ ]:
tensor.to("cuda")

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor.numpy()

array([1, 2, 3])

In [ ]:
tensor_gpu = tensor.to("cuda")
tensor_gpu.numpy()

TypeError: ignored

In [ ]:
tensor_gpu.cpu()

tensor([1, 2, 3])

In [ ]:
import torch
import torch.nn.functional as F

# 假设x是一个大小为(3, 4)的tensor
x = torch.randn(3, 4)

# 对x进行标准化处理，dim指定哪个维度上进行标准化
normalized_x = F.normalize(x, p=2, dim=1)

print(normalized_x.shape)  # 输出：torch.Size([3, 4])


torch.Size([3, 4])


In [ ]:
x = torch.tensor([[1.0,2],[3,4]])
F.normalize(x, p=2, dim=1)

tensor([[0.4472, 0.8944],
        [0.6000, 0.8000]])

In [ ]:
normalized_x

tensor([[ 0.1653, -0.6754, -0.7046, -0.1416],
        [ 0.4463,  0.1988,  0.0587,  0.8705],
        [-0.2529, -0.7647, -0.5417,  0.2405]])